sudo: required
services:
  - docker

before_install:
  - docker build -t architraigupta/travis-demoapp -f demoapp/Dockerfile.dev demoapp

script:
  - docker run -e CI=true architraigupta/travis-demoapp npm run test -- --coverage